export const REGISTER_SUCCESS: 'REGISTER_SUCCESS' = 'REGISTER_SUCCESS';
export const REGISTER_FAILED: 'REGISTER_FAILED' = 'REGISTER_FAILED';
export const REGISTER: 'REGISTER' = 'REGISTER';

export const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = 'LOGIN_SUCCESS';
export const LOGIN_FAILED: 'LOGIN_FAILED' = 'LOGIN_FAILED';
export const LOGIN: 'LOGIN' = 'LOGIN';

export const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED: 'LOGOUT_FAILED' = 'LOGOUT_FAILED';
export const LOGOUT: 'LOGOUT' = 'LOGOUT';

export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS';
export const GET_USER_FAILED: 'GET_USER_FAILED' = 'GET_USER_FAILED';
export const GET_USER: 'GET_USER' = 'GET_USER';

export const FORGOT_PW_SUCCESS: 'FORGOT_PW_SUCCESS' = 'FORGOT_PW_SUCCESS';
export const FORGOT_PW_FAILED: 'FORGOT_PW_FAILED' = 'FORGOT_PW_FAILED';
export const FORGOT_PW: 'FORGOT_PW' = 'FORGOT_PW';

export const RESET_PW_SUCCESS: 'RESET_PW_SUCCESS' = 'RESET_PW_SUCCESS';
export const RESET_PW_FAILED: 'RESET_PW_FAILED' = 'RESET_PW_FAILED';
export const RESET_PW: 'RESET_PW' = 'RESET_PW';

export const UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS' = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED: 'UPDATE_USER_FAILED' = 'UPDATE_USER_FAILED';
export const UPDATE_USER: 'UPDATE_USER' = 'UPDATE_USER'; 

export const REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS' = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILED: 'REFRESH_TOKEN_FAILED' = 'REFRESH_TOKEN_FAILED';
export const REFRESH_TOKEN: 'REFRESH_TOKEN' = 'REFRESH_TOKEN';
