export const GET_ITEMS : 'GET_ITEMS' = 'GET_ITEMS';
export const GET_ITEMS_SUCCESS: 'GET_ITEMS_SUCCESS' = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAILED: 'GET_ITEMS_FAILED' = 'GET_ITEMS_FAILED';
export const INCREASE_ITEM: 'INCREASE_ITEM' = 'INCREASE_ITEM';
export const DECREASE_ITEM: 'DECREASE_ITEM' = 'DECREASE_ITEM';
export const CLEAR_QTY: 'CLEAR_QTY' = 'CLEAR_QTY';